# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
 
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob $(pipelinevalue)
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob $(pipelinevalue)

- stage: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    variables: 
      environment: Dev
    steps:
    - bash: echo DevDeployJob $(environment)

- stage: QA
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob

- stage: Prod
  dependsOn: 
  - Dev
  - QA
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob
