# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

# pool:
#   vmImage: $(operatingSystem)

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: Build
      steps:
      - script: echo Build

  - stage: Dev
    jobs:
    - deployment: DevDeploy
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo DevDeploy

  - stage: QA
    jobs:
    - deployment: QADeploy
      environment: QA
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo QADeploy. This will only be successful after manual approval!
          
    

